coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 50%

    patch:
      default:
        target: 50%

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default